/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface DaePost {
    'article': string;
    'date': string;
    'description': string;
    'image': string;
    'tags': string;
  }
  interface DaeTags {
    'tags': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLDaePostElement extends Components.DaePost, HTMLStencilElement {}
  var HTMLDaePostElement: {
    prototype: HTMLDaePostElement;
    new (): HTMLDaePostElement;
  };

  interface HTMLDaeTagsElement extends Components.DaeTags, HTMLStencilElement {}
  var HTMLDaeTagsElement: {
    prototype: HTMLDaeTagsElement;
    new (): HTMLDaeTagsElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'dae-post': HTMLDaePostElement;
    'dae-tags': HTMLDaeTagsElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface DaePost extends JSXBase.HTMLAttributes<HTMLDaePostElement> {
    'article'?: string;
    'date'?: string;
    'description'?: string;
    'image'?: string;
    'tags'?: string;
  }
  interface DaeTags extends JSXBase.HTMLAttributes<HTMLDaeTagsElement> {
    'tags'?: string;
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'dae-post': DaePost;
    'dae-tags': DaeTags;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


